name: Docker Image CI

on:
    push:
      branches: [ "master" ]

jobs:

    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub Container Registry
        uses: docker/login-action@v3
        with:
          username: suro4ek
          password: ${{ secrets.TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./dockerfiles/base
          platforms: linux/arm64
          push: true
          tags: suro4ek/fenics-base:2.0
